/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DocumentViewer: typeof import('./components/DocumentViewer.vue')['default']
    Excel: typeof import('./components/preview/Excel.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GiscusComment: typeof import('./components/GiscusComment.vue')['default']
    IconCarbonArchive: typeof import('~icons/carbon/archive')['default']
    IconCarbonArrowLeft: typeof import('~icons/carbon/arrow-left')['default']
    IconCarbonArrowRight: typeof import('~icons/carbon/arrow-right')['default']
    IconCarbonBook: typeof import('~icons/carbon/book')['default']
    IconCarbonCalendar: typeof import('~icons/carbon/calendar')['default']
    IconCarbonChevronRight: typeof import('~icons/carbon/chevron-right')['default']
    IconCarbonClose: typeof import('~icons/carbon/close')['default']
    IconCarbonCopy: typeof import('~icons/carbon/copy')['default']
    IconCarbonDocument: typeof import('~icons/carbon/document')['default']
    IconCarbonDocumentBlank: typeof import('~icons/carbon/document-blank')['default']
    IconCarbonEmail: typeof import('~icons/carbon/email')['default']
    IconCarbonFaceDizzy: typeof import('~icons/carbon/face-dizzy')['default']
    IconCarbonFolder: typeof import('~icons/carbon/folder')['default']
    IconCarbonFolderOpen: typeof import('~icons/carbon/folder-open')['default']
    IconCarbonHome: typeof import('~icons/carbon/home')['default']
    IconCarbonLanguage: typeof import('~icons/carbon/language')['default']
    IconCarbonLocked: typeof import('~icons/carbon/locked')['default']
    IconCarbonLogoFacebook: typeof import('~icons/carbon/logo-facebook')['default']
    IconCarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    IconCarbonLogoLinkedin: typeof import('~icons/carbon/logo-linkedin')['default']
    IconCarbonLogout: typeof import('~icons/carbon/logout')['default']
    IconCarbonLogoWechat: typeof import('~icons/carbon/logo-wechat')['default']
    IconCarbonMenu: typeof import('~icons/carbon/menu')['default']
    IconCarbonMoon: typeof import('~icons/carbon/moon')['default']
    IconCarbonPinFilled: typeof import('~icons/carbon/pin-filled')['default']
    IconCarbonRecentlyViewed: typeof import('~icons/carbon/recently-viewed')['default']
    IconCarbonSearch: typeof import('~icons/carbon/search')['default']
    IconCarbonStar: typeof import('~icons/carbon/star')['default']
    IconCarbonSun: typeof import('~icons/carbon/sun')['default']
    IconCarbonTime: typeof import('~icons/carbon/time')['default']
    IconComponent: typeof import('./components/ui/IconComponent.vue')['default']
    MarqueeNotice: typeof import('./components/ui/MarqueeNotice.vue')['default']
    NavTree: typeof import('./components/NavTree.vue')['default']
    PasswordProtection: typeof import('./components/PasswordProtection.vue')['default']
    PdfToHtml: typeof import('./components/preview/PdfToHtml.vue')['default']
    RecentArticles: typeof import('./components/RecentArticles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchModal: typeof import('./components/ui/SearchModal.vue')['default']
    ShareModal: typeof import('./components/ui/ShareModal.vue')['default']
    ThemeToggle: typeof import('./components/ui/ThemeToggle.vue')['default']
  }
}
